### PR TITLE
Fix telegram source link

### PR DESCRIPTION
**Pull request by grebenschikov**
https://github.com/overtake/telegram is OS X version.

### CODE REVIEW

**Comment by ank91** [comment]
what about this:
https://github.com/telegramdesktop/tdesktop

**Comment by grebenschikov** [comment]
yes, it's right link

**Comment by VoLuong** [comment]
Thank you

**Comment by VoLuong** [comment]
Actually I heard someone on a forum reported that and then fixed it locally. Right after I pushed it i came here to check and see your pull request hahah. Luckily it is still fine to merge your commit. Thank you again.

**Pull request merged**
